name: Deploy to Server

on:
  push:
    branches:
      - main   # или твоя рабочая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh root@95.81.117.141 "
            cd /var/www/adeita.online &&
            git pull origin main &&
            npm install &&
            pm2 restart adeita
          "